spring:
  application:
    name: bible-references
  profiles:
    active: local-insecure
  threads:
    virtual:
      enabled: false
  cloud:
    config:
      # Se usa cuando spring.cloud.config.enabled es true
      enabled: false
      uri: http://config-service:8080
      name: ${spring.application.name}
      label: master
      profile: ${spring.profiles.active}
  config:
    # Se usa en entorno LOCAL, cuando spring.cloud.config.enabled es false
    name: ${spring.application.name}
  datasource:
    url: jdbc:postgresql://localhost:5432/bible_db?currentSchema=bible_schema
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: hazelcast
    cache-names: verses, sourceWords, compoundWords, keywordCounts, compoundWordCounts, keywordTranslatedCounts, compoundTranslatedCounts, keywordTransliteratedWord, compoundTransliteratedWord

# Dominio del frontend (CloudFront). Reemplazar por su dominio, por ejemplo: https://d123.cloudfront.net
app:
  frontend:
    origin: "https://escrituraclave.com"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.gdav: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
