spring:
  application:
    name: bible-references
  datasource:
    url: jdbc:postgresql://localhost:5432/bible_db?currentSchema=bible_schema
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: hazelcast
    cache-names: verses